[package]
name = "russ"
version = "0.1.0"
authors = ["Clark Kampfe <clark.kampfe@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
atom_syndication = { version = "0.11", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
copypasta = "0.7"
crossterm = "0.20"
diligent-date-parser = "0.1"
futures-util = "0.3"
html2text = "0.2"
num_cpus = "1.13"
r2d2 = "0.8"
r2d2_sqlite = "0.19"
rss = { version = "2.0", default-features = false }
rusqlite = { version = "0.26", features = ["bundled", "chrono"] }
structopt = "0.3"
tokio = { version = "1", features = ["rt", "time"] }
tui = { version = "0.16", default-features = false, features = ["crossterm"] }
ureq = "2.3"
wsl = "0.1"
webbrowser = { git = "https://github.com/codota/webbrowser-rs", branch = "feature/add-suppress-output-flag-with-docs" }

[profile.release]
codegen-units = 1
lto = true
